Return-Path: <linux-integrity-owner@vger.kernel.org>
X-Original-To: lists+linux-integrity@lfdr.de
Delivered-To: lists+linux-integrity@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 6D48425B2B
	for <lists+linux-integrity@lfdr.de>; Wed, 22 May 2019 02:30:52 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1728084AbfEVAav (ORCPT <rfc822;lists+linux-integrity@lfdr.de>);
        Tue, 21 May 2019 20:30:51 -0400
Received: from mx0b-001b2d01.pphosted.com ([148.163.158.5]:60248 "EHLO
        mx0a-001b2d01.pphosted.com" rhost-flags-OK-OK-OK-FAIL)
        by vger.kernel.org with ESMTP id S1726083AbfEVAav (ORCPT
        <rfc822;linux-integrity@vger.kernel.org>);
        Tue, 21 May 2019 20:30:51 -0400
Received: from pps.filterd (m0098416.ppops.net [127.0.0.1])
        by mx0b-001b2d01.pphosted.com (8.16.0.27/8.16.0.27) with SMTP id x4M0LvQe016735
        for <linux-integrity@vger.kernel.org>; Tue, 21 May 2019 20:30:50 -0400
Received: from e06smtp07.uk.ibm.com (e06smtp07.uk.ibm.com [195.75.94.103])
        by mx0b-001b2d01.pphosted.com with ESMTP id 2sms0hwkk5-1
        (version=TLSv1.2 cipher=AES256-GCM-SHA384 bits=256 verify=NOT)
        for <linux-integrity@vger.kernel.org>; Tue, 21 May 2019 20:30:49 -0400
Received: from localhost
        by e06smtp07.uk.ibm.com with IBM ESMTP SMTP Gateway: Authorized Use Only! Violators will be prosecuted
        for <linux-integrity@vger.kernel.org> from <zohar@linux.ibm.com>;
        Wed, 22 May 2019 01:30:48 +0100
Received: from b06cxnps4076.portsmouth.uk.ibm.com (9.149.109.198)
        by e06smtp07.uk.ibm.com (192.168.101.137) with IBM ESMTP SMTP Gateway: Authorized Use Only! Violators will be prosecuted;
        (version=TLSv1/SSLv3 cipher=AES256-GCM-SHA384 bits=256/256)
        Wed, 22 May 2019 01:30:45 +0100
Received: from d06av22.portsmouth.uk.ibm.com (d06av22.portsmouth.uk.ibm.com [9.149.105.58])
        by b06cxnps4076.portsmouth.uk.ibm.com (8.14.9/8.14.9/NCO v10.0) with ESMTP id x4M0UiWk52035656
        (version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384 bits=256 verify=OK);
        Wed, 22 May 2019 00:30:44 GMT
Received: from d06av22.portsmouth.uk.ibm.com (unknown [127.0.0.1])
        by IMSVA (Postfix) with ESMTP id 3F7254C04A;
        Wed, 22 May 2019 00:30:44 +0000 (GMT)
Received: from d06av22.portsmouth.uk.ibm.com (unknown [127.0.0.1])
        by IMSVA (Postfix) with ESMTP id C687E4C05A;
        Wed, 22 May 2019 00:30:43 +0000 (GMT)
Received: from localhost.localdomain (unknown [9.80.110.214])
        by d06av22.portsmouth.uk.ibm.com (Postfix) with ESMTP;
        Wed, 22 May 2019 00:30:43 +0000 (GMT)
Subject: Re: IMA signature generated by evmctl has unexpected key identifier
From:   Mimi Zohar <zohar@linux.ibm.com>
To:     Lakshmi <nramas@linux.microsoft.com>,
        linux-integrity@vger.kernel.org
Date:   Tue, 21 May 2019 20:30:33 -0400
In-Reply-To: <cea244c1-f457-cdc0-e39b-c9381cb4dc79@linux.microsoft.com>
References: <alpine.LRH.2.21.1905092048590.7180@linuxonhyperv3.guj3yctzbm1etfxqx2vob5hsef.xx.inter>
         <90a4d769-4c32-4b2b-ceaa-6e0980d5c193@linux.microsoft.com>
         <1557854750.4139.65.camel@linux.ibm.com>
         <4b810e48-6ddc-19d0-9fc1-70cd29c7c01b@linux.microsoft.com>
         <1557869914.4139.73.camel@linux.ibm.com>
         <5d1ab46e-ea01-b7a7-4a9b-6e4bcb63c331@linux.microsoft.com>
         <cea244c1-f457-cdc0-e39b-c9381cb4dc79@linux.microsoft.com>
Content-Type: text/plain; charset="UTF-8"
X-Mailer: Evolution 3.20.5 (3.20.5-1.fc24) 
Mime-Version: 1.0
Content-Transfer-Encoding: 8bit
X-TM-AS-GCONF: 00
x-cbid: 19052200-0028-0000-0000-000003702171
X-IBM-AV-DETECTION: SAVI=unused REMOTE=unused XFE=unused
x-cbparentid: 19052200-0029-0000-0000-0000242FCD4A
Message-Id: <1558485033.4039.215.camel@linux.ibm.com>
X-Proofpoint-Virus-Version: vendor=fsecure engine=2.50.10434:,, definitions=2019-05-21_07:,,
 signatures=0
X-Proofpoint-Spam-Details: rule=outbound_notspam policy=outbound score=0 priorityscore=1501
 malwarescore=0 suspectscore=0 phishscore=0 bulkscore=0 spamscore=0
 clxscore=1015 lowpriorityscore=0 mlxscore=0 impostorscore=0
 mlxlogscore=999 adultscore=0 classifier=spam adjust=0 reason=mlx
 scancount=1 engine=8.0.1-1810050000 definitions=main-1905220001
Sender: linux-integrity-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-integrity.vger.kernel.org>
X-Mailing-List: linux-integrity@vger.kernel.org

On Tue, 2019-05-21 at 10:48 -0700, Lakshmi wrote:
> On 5/14/19 3:07 PM, Lakshmi wrote:
> >>
> >> I should have asked you to make sure that the last 8 bytes of "X509v3
> >> Subject Key Identifier" in the certificate used to sign the kernel
> >> image is the same as above.
> >>
> >> Mimi
> >>
> > 
> > Yes - the Subject Key Identifier matches the output from keyctl.
> > 
> > Please see below:
> > 
> > X509v3 Subject Key Identifier:
> >                  
> > 85:51:2D:09:FC:12:C7:F3:8B:96:79:35:26:51:DC:B3:65:90:33:36
> 
> Please let me know if you need more information\logs on this issue.

Have you tried using "evmctl ima_verify" to verify the signature after
signing the file?

Perhaps it's something with the key.  If you haven't already used the
scripts for generating the keys in the ima-evm-utils examples/
directory, you might try that.

I just pushed out the ima-evm-utils master branch.  See if the new
"master" branch works.

Mimi

